version: '3.8'

services:
#  app:
#    build:
#      context: /
#      dockerfile: /Dockerfile
#    container_name: data_app
#    ports:
#      - "8000:8000"  # אפליקציה
#    environment:
#      DATABASE_URL: "postgresql://admin:1234@postgres:5432/personal_financial_assistant"
#    depends_on:
#      - postgres
#    volumes:
#      - .:/app

  db-sql:
    image: postgres:17
    container_name: postgres_container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: personal_financial_assistant
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data:
